name: flutter_presentation
description: Presentation about Flutter implemented using Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flare_flutter: ^3.0.0
  flutter:
    sdk: flutter
  flutter_card_swipper: ^0.4.0
  flutter_svg: ^0.21.0+1
  lint: ^1.5.3
  web_browser: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/flare/
